(print "==============================")
(print "    30秒カウントダウンタイマー")
(print "==============================")
(print "")
(print "カウントダウン開始...")
(print "")
(print "30秒...")
(sleep 5)
(print "25秒...")
(sleep 5)
(print "20秒...")
(sleep 5)
(print "15秒...")
(sleep 5)
(print "10秒...")
(sleep 5)
(print "5秒...")
(sleep 1)
(print "4秒...")
(sleep 1)
(print "3秒...")
(sleep 1)
(print "2秒...")
(sleep 1)
(print "1秒...")
(sleep 1)
(print "")
(print "*** 時間終了！ ***")
(print "")
(print "==============================")
(print "    タイマー完了")
(print "==============================")
