;; 30秒カウントダウンタイマー (ループ版)
;; ASCII文字のみを使用したシンプルなタイマー

(print "==============================")
(print "    30秒カウントダウンタイマー")
(print "    (1秒間隔版)")
(print "==============================")
(print "")

(print "カウントダウン開始...")
(print "")

;; 30秒から1秒ずつカウントダウン
(print "30") (sleep 1)
(print "29") (sleep 1)
(print "28") (sleep 1)
(print "27") (sleep 1)
(print "26") (sleep 1)
(print "25") (sleep 1)
(print "24") (sleep 1)
(print "23") (sleep 1)
(print "22") (sleep 1)
(print "21") (sleep 1)
(print "20") (sleep 1)
(print "19") (sleep 1)
(print "18") (sleep 1)
(print "17") (sleep 1)
(print "16") (sleep 1)
(print "15") (sleep 1)
(print "14") (sleep 1)
(print "13") (sleep 1)
(print "12") (sleep 1)
(print "11") (sleep 1)
(print "10") (sleep 1)
(print "9") (sleep 1)
(print "8") (sleep 1)
(print "7") (sleep 1)
(print "6") (sleep 1)
(print "5") (sleep 1)
(print "4") (sleep 1)
(print "3") (sleep 1)
(print "2") (sleep 1)
(print "1") (sleep 1)

(print "")
(print "*** 時間終了！ ***")
(print "")
(print "==============================")
(print "    タイマー完了")
(print "==============================")
